export const JOB_REPOSITORY = Symbol('JOB_REPOSITORY');
export const JOB_QUESTION_REPOSITORY = Symbol('JOB_QUESTION_REPOSITORY');
export const JOB_QUESTION_ANSWER_REPOSITORY = Symbol('JOB_QUESTION_ANSWER_REPOSITORY');
export const JOB_FEEDBACK_REPOSITORY = Symbol('JOB_FEEDBACK_REPOSITORY');