export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const USER_TOKEN_REPOSITORY = Symbol('USER_TOKEN_REPOSITORY');
export const USER_PROVIDER_REPOSITORY = Symbol('USER_PROVIDER_REPOSITORY');
export const USER_PROFILE_REPOSITORY = Symbol('USER_PROFILE_REPOSITORY');
export const ROLE_REPOSITORY = Symbol('ROLE_REPOSITORY');
export const PERMISISON_REPOSITORY = Symbol('PERMISISON_REPOSITORY');
export const USER_TEMPORARY_PERMISSION_REPOSITORY = Symbol('USER_TEMPORARY_PERMISSION_REPOSITORY');
export const PERMISSION_REPOSITORY = Symbol('PERMISSION_REPOSITORY');